# Generated by Django 5.0.2 on 2024-03-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_hond_delete_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="hond",
            name="zichtbaar_op_site",
            field=models.BooleanField(default=False),
        ),
    ]
